version: '3.3'
services:
  db:
    image: mysql:8.1.0
    restart: always
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 60s
      retries: 10
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
      - ./data/sqlite_FireApp_data.sql:/docker-entrypoint-initdb.d/sqlite_FireApp_data.sql
  fireapp:
    image: ghcr.io/techlauncherfireapp/backend:latest
    environment:
      username: 'user'
      password: 'password'
      host: 'db'
      port: '3306'
      dbname: 'db'
    ports:
      - '5000:5000'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./google-credentials.json:/app/google-credentials.json
volumes:
  my-db:
